package model.Item;

import model.App;
import model.Map.Tile;

public enum ItemType {
    CHERRY_BOMB("Cherry Bomb"),
    BOMB("Bomb"),
    MEGA_BOMB("Mega Bomb"),
    SPRINKLER("Sprinkler"),
    QUALITY_SPRINKLER("Quality Sprinkler"),
    IRIDIUM_SPRINKLER("Iridium Sprinkler"),
    CHARCOAL_KILN("Charcoal Klin"),
    FURNACE("Furnace"),
    SCARECROW("Scarecrow"),
    DELUXE_SCARECROW("Deluxe Scarecrow"),
    BEE_HOUSE("Bee House"),
    CHEESE_PRESS("Cheese Press"),
    KEG("Keg"),
    LOOM("Loom"),
    MAYONNAISE_MACHINE("Mayonnaise Machine"),
    OIL_MAKER("Oil Maker"),
    PRESERVES_JAR("Preserves Jar"),
    DEHYDRATOR("Dehydrator"),
    GRASS_STARTER("Grass Starter"),
    FISH_SMOKER("Fish Smoker"),
    MYSTIC_TREE_SEED("Mystic Tree Seed"),

    QUARTZ("Quartz"),
    EARTH_CRYSTAL("Earth Crystal"),
    FROZEN_TEAR("Frozen Tear"),
    FIRE_QUARTZ("Fire Quartz"),
    EMERALD("Emerald"),
    AQUAMARINE("Aquamarine"),
    RUBY("Ruby"),
    AMETHYST("Amethyst"),
    TOPAZ("Topaz"),
    JADE("Jade"),
    DIAMOND("Diamond"),
    PRISMATIC_SHARD("Prismatic Shard"),
    COPPER("Copper"),
    IRON("Iron"),
    GOLD("Gold"),
    IRIDIUM("Iridium"),
    COAL("Coal"),

    COPPER_ORE("copper ore"),
    IRON_ORE("iron ore"),
    GOLD_ORE("gold ore"),
    COPPER_BAR("copper bar"),
    IRON_BAR("iron bar"),
    GOLD_BAR("gold bar"),
    IRIDIUM_BAR("iridium bar"),
    WOOD("wood"),
    STONE("stone"),
    IRIDIUM_ORE("iridium ore"),
    ACORN("acorn"),
    MAPLE_SEED("maple seed"),
    PINE_CONE("pine cone"),
    MAHOGANY_SEED("mahogany seed"),
    WOOL("Wool"),
    CHERRY_BOMB_RECIPE("Cherry Bomb"),
    BOMB_RECIPE("Bomb"),
    MEGA_BOMB_RECIPE("Mega Bomb"),
    SPRINKLER_RECIPE("Sprinkler"),
    QUALITY_SPRINKLER_RECIPE("Quality Sprinkler"),
    IRIDIUM_SPRINKLER_RECIPE("Iridium Sprinkler"),
    CHARCOAL_KILN_RECIPE("Charcoal Klin"),
    FURNACE_RECIPE("Furnace"),
    SCARECROW_RECIPE("Scarecrow"),
    DELUXE_SCARECROW_RECIPE("Deluxe Scarecrow"),
    BEE_HOUSE_RECIPE("Bee House"),
    CHEESE_PRESS_RECIPE("Cheese Press"),
    KEG_RECIPE("Keg"),
    LOOM_RECIPE("Loom"),
    MAYONNAISE_MACHINE_RECIPE("Mayonnaise Machine"),
    OIL_MAKER_RECIPE("Oil Maker"),
    PRESERVES_JAR_RECIPE("Preserves Jar"),
    DEHYDRATOR_RECIPE("Dehydrator"),
    GRASS_STARTER_RECIPE("Grass Starter"),
    FISH_SMOKER_RECIPE("Fish Smoker"),
    MYSTIC_TREE_SEED_RECIPE("Mystic Tree Seed"),


    FIBER("fiber"),
    BARN("barn"),
    BIG_BARN("big barn"),
    DELUXE_BARN("deluxe barn"),
    COOP("coop"),
    BIG_COOP("big coop"),
    DELUXE_COOP("deluxe coop"),
    WELL("well"),
    SHIPPING_BIN("shipping bin"),

    HAY("hay"),
    SHEARS("shears"),
    MILK_PAIR("milk pair"),
    FRIED_EGG("fried egg"),
    BAKED_FISH("baked fish"),
    SALAD("salad"),
    OMELET("omelet"),
    PUMPKIN_PIE("pumpkin pie"),
    SPAGHETTI("spaghetti"),
    PIZZA("pizza"),
    TORTILLA("tortilla"),
    MAKI_ROLL("maki roll"),
    TRIPLE_SHOT_ESPRESSO("triple shot espresso"),
    COOKIE("cookie"),
    PANCAKE("pancake"),
    FRUIT_SALAD("fruit salad"),
    RED_PLATE("red plate"),
    SALMON_DINNER("salmon dinner"),
    VEGETABLE_MEDLEY("vegetable medley"),
    FARMER_LUNCH("farmer's lunch"),
    SURVIVAL_BURGER("survival burger"),
    DISH_O_THE_SEA("dish O' the Sea"),
    SEAFORM_PUDDING("seaform pudding"),
    MINER_TREAT("miner's treat"),
    PANCAKES("pancakes"),
    HASH_BROWNS("hash browns"),
    FARMERS_LUNCH("farmers lunch"),
    SEAFOAM_PUDDING("seafoam pudding"),
    MINERS_TREAT("miners treat"),

    HARD_WOOD("hard wood"),
    LevelUpFriendship("level up friendship"),


    EGG("egg"),
    BIG_EGG("big egg"),
    SARDINE("sardine"),
    SALMON("salmon"),
    WHEAT("wheat"),
    LEEK("leek"),
    DANDELION("dandelion"),
    MILK("milk"),
    PUMPKIN("pumpkin"),
    WHEAT_FLOWER("wheat flower"),
    TOMATO("tomato"),
    CHEESE("cheese"),
    CORN("corn"),
    RICE("rice"),
    COFFEE("coffee"),
    SUGAR("sugar"),
    POTATO("potato"),
    OIL("oil"),
    BLUEBERRY("blueberry"),
    MELON("melon"),
    APRICOT("apricot"),
    GRAPES("grapes"),
    CHERRY("cherry"),
    BANANA("banana"),
    MANGO("mango"),
    ORANGE("orange"),
    PEACH("peach"),
    POMEGRANATE("pomegranate"),
    APPLE("apple"),
    OAK_RESIN("oak resin"),
    MAPLE_SYRUP("maple syrup"),
    PINE_TAR("pine tar"),
    SAP("sap"),
    COMMON_MUSHROOM("common mushroom"),
    MYSTIC_SYRUP("mystic syrup"),
    RED_CABBAGE("red cabbage"),
    RADISH("radish"),
    AMARANTH("amaranth"),
    KALE("kale"),
    BEET("beet"),
    PARSNIP("parsnip"),
    BREAD("bread"),
    CARROT("carrot"),
    EGGPLANT("eggplant"),
    HASH_BROWN("hash brown"),
    FLOUNDER("flounder"),
    WHEAT_FLOUR("wheat flour"),
    ANY_FISH("any fish"),
    MIDNIGHT_CARP("midnight carp"),
    COOPER_TRASHCAN("cooper trashcan"),
    STEEL_TRASHCAN("steel trashcan"),
    GOLD_TRASHCAN("gold trashcan"),
    IRIDIUM_TRASHCAN("iridium trashcan"),
    COPPER_TOOL("copper tool"),
    STEEL_TOOL("steel tool"),
    GOLD_TOOL("gold tool"),
    IRIDIUM_TOOL("iridium tool"),
    PICKLE("pickle"),

    BEER("beer"),
    HASH_BROWNS_RECIPE("hash browns recipe"),
    PIZZA_RECIPE("pizza recipe"),
    OMELET_RECIPE("omelet recipe"),
    BREAD_RECIPE("bread recipe"),
    PANCAKES_RECIPE("pancakes recipe"),
    TORTILLA_RECIPE("tortilla recipe"),
    MAKI_ROLL_RECIPE("maki roll recipe"),
    TRIPLE_SHOT_ESPRESSO_RECIPE("triple shot espresso recipe"),
    COOKIE_RECIPE("cookie recipe"),

    JOJA_COLA("joja cola"),
    ANCIENT_SEED("ancient seed"),
    PARSNIP_SEEDS("parsnip seeds"),
    BEAN_STARTER("bean starter"),
    CAULI_FLOWER_SEEDS("cauli flower seeds"),
    POTATO_SEEDS("potato seeds"),
    STRAWBERRY_SEEDS("strawberry seeds"),
    CALE_SEEDS("cale seeds"),
    CARROT_SEEDS("carrot seeds"),
    RHUBARB_SEEDS("rhubarb seeds"),
    JAZZ_SEEDS("jazz seeds"),
    TULIP_BULB("tulip bulb"),
    COFFEE_BEANS("coffee beans"),
    TOMATO_SEEDS("tomato seeds"),
    PEPPER_SEEDS("pepper seeds"),
    WHEAT_SEEDS("wheat seeds"),
    SUMMER_SQUASH_SEEDS("summer squash seeds"),
    RADISH_SEEDS("radish seeds"),
    MELON_SEEDS("melon seeds"),
    HOPS_STARTER("hops starter"),
    POPPY_SEEDS("poppy seeds"),
    SPANGLE_SEEDS("spangle seeds"),
    STARFRUIT_SEEDS("starfruit seeds"),
    SUNFLOWER_SEEDS("sunflower seeds"),
    CORN_SEEDS("corn seeds"),
    EGGPLANT_SEEDS("eggplant seeds"),
    PUMPKIN_SEEDS("pumpkin seeds"),
    BROCCOLI_SEEDS("broccoli seeds"),
    AMARANTH_SEEDS("amaranth seeds"),
    GRAPE_STARTER("grape starter"),
    BEET_SEEDS("beet seeds"),
    YAM_SEEDS("yam seeds"),
    BOK_CHOY_SEEDS("bok choy seeds"),
    CRANBERRY_SEEDS("cranberry seeds"),
    FAIRY_SEEDS("fairy seeds"),
    RARE_SEED("rare seed"),
    POWDERMELON_SEEDS("powdermelon seeds"),
    BOUQUET("bouquet"),
    WEDDING_RING("wedding ring"),
    VINEGAR("vinegar"),
    DELUXE_RETAINING_SOIL("deluxe retaining soil"),
    SPEED_GRO("speed-gro"),
    APPLE_SAPLING("apple sapling"),
    APRICOT_SAPLING("apricot sapling"),
    CHERRY_SAPLING("cherry sapling"),
    ORANGE_SAPLING("orange sapling"),
    PEACH_SAPLING("peach sapling"),
    POMEGRANATE_SAPLING("pomegranate sapling"),
    BASIC_RETAINING_SOIL("basic retaining soil"),
    QUALITY_RETAINING_SOIL("quality retaining soil"),
    CAULIFLOWER_SEEDS("cauliflower seeds"),
    KALE_SEEDS("kale seeds"),
    GARLIC_SEEDS("garlic seeds"),
    RICE_SHOOT("rice shoot"),
    BLUEBERRY_SEEDS("blueberry seeds"),
    RED_CABBAGE_SEEDS("red cabbage seeds"),
    ARTICHOKE_SEEDS("artichoke seeds"),
    TROUT_SOUP("trout soup"),
    BAMBOO_POLE("bamboo pole"),
    TRAINING_ROD("training rod"),
    FIBERGLASS_ROD("fiberglass rod"),
    IRIDIUM_ROD("iridium rod"),

    CHICKEN("chicken"),
    COW("cow"),
    DUCK("duck"),
    SHEEP("sheep"),
    GOAT("goat"),
    RABBIT("rabbit"),
    DINOSAUR("dinosaur"),
    PIG("pig"),

    DUMMY("dummy"),

    LARGE_PACK("large backpack"),
    DELUXE_PACK("deluxe backpack");


    private final String DisplayName;

    ItemType(String DisplayName) {
        this.DisplayName = DisplayName;
    }

    @Override
    public String toString() {
        return name();
    }

    public static ItemType getItemType(String name) {

        for (ItemType itemType : ItemType.values()) {
            if (itemType.getDisplayName().equalsIgnoreCase(name)) {
                return itemType;
            }
        }
        return null;
    }

    public String getDisplayName() {
        return this.DisplayName;
    }
}
