package com.StardewValley.model.Item;

import com.StardewValley.enums.Seasons;
import com.StardewValley.model.App;
import com.StardewValley.model.Map.Tile;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.graphics.Texture;

public enum ItemType {
    CHERRY_BOMB("Cherry Bomb",new Texture(Gdx.files.internal("Crafting/Cherry_Bomb.png"))),
    BOMB("Bomb", new Texture(Gdx.files.internal("Crafting/Bomb.png"))),
    MEGA_BOMB("Mega Bomb", new Texture(Gdx.files.internal("Crafting/Mega_Bomb.png"))),
    SPRINKLER("Sprinkler", new Texture(Gdx.files.internal("Crafting/Sprinkler.png"))),
    QUALITY_SPRINKLER("Quality Sprinkler", new Texture(Gdx.files.internal("Crafting/Quality_Sprinkler.png"))),
    IRIDIUM_SPRINKLER("Iridium Sprinkler", new Texture(Gdx.files.internal("Crafting/Iridium_Sprinkler.png"))),
    CHARCOAL_KILN("Charcoal Klin"),
    FURNACE("Furnace",new Texture(Gdx.files.internal("Crafting/Furnace.png"))),
    SCARECROW("Scarecrow",new Texture(Gdx.files.internal("Crafting/Scarecrow.png"))),
    DELUXE_SCARECROW("Deluxe Scarecrow", new Texture(Gdx.files.internal("Crafting/Deluxe_Scarecrow.png"))),
    BEE_HOUSE("Bee House", new Texture(Gdx.files.internal("Crafting/Bee_House.png"))),
    CHEESE_PRESS("Cheese Press", new Texture(Gdx.files.internal("Crafting/Cheese_Press.png"))),
    KEG("Keg", new Texture(Gdx.files.internal("Crafting/Keg.png"))),
    LOOM("Loom", new Texture(Gdx.files.internal("Crafting/Loom.png"))),
    MAYONNAISE_MACHINE("Mayonnaise Machine", new Texture(Gdx.files.internal("Crafting/Mayonnaise_Machine.png"))),
    OIL_MAKER("Oil Maker", new Texture(Gdx.files.internal("Crafting/OIL_Maker.png"))),
    PRESERVES_JAR("Preserves Jar", new Texture(Gdx.files.internal("Crafting/Preserves_Jar.png"))),
    DEHYDRATOR("Dehydrator", new Texture(Gdx.files.internal("Crafting/Dehydrator.png"))),
    GRASS_STARTER("Grass Starter", new Texture(Gdx.files.internal("Crafting/Grass_Starter.png"))),
    FISH_SMOKER("Fish Smoker", new Texture(Gdx.files.internal("Crafting/Fish_Smoker.png"))),
    MYSTIC_TREE_SEED("Mystic Tree Seed", new Texture(Gdx.files.internal("Crafting/Mystic_Tree_Seed.png"))),

    QUARTZ("Quartz", new Texture(Gdx.files.internal("Mineral/Quartz.png"))),
    EARTH_CRYSTAL("Earth Crystal", new Texture(Gdx.files.internal("Mineral/Earth_Crystal.png"))),
    FROZEN_TEAR("Frozen Tear", new Texture(Gdx.files.internal("Mineral/Frozen_Tear.png"))),
    FIRE_QUARTZ("Fire Quartz", new Texture(Gdx.files.internal("Mineral/Fire_Quartz.png"))),
    EMERALD("Emerald"),
    AQUAMARINE("Aquamarine"),
    RUBY("Ruby"),
    AMETHYST("Amethyst"),
    TOPAZ("Topaz"),
    JADE("Jade"),
    DIAMOND("Diamond"),
    PRISMATIC_SHARD("Prismatic Shard", new Texture(Gdx.files.internal("Crafting/Prismatic_Shard.png"))),
    COPPER("Copper"),
    IRON("Iron"),
    GOLD("Gold", new Texture(Gdx.files.internal("Crafting/Gold.png"))),
    IRIDIUM("Iridium"),
    COAL("Coal", new Texture(Gdx.files.internal("Crafting/Coal.png"))),

    COPPER_ORE("copper ore", new Texture(Gdx.files.internal("Resource/Copper_ore.png"))),
    IRON_ORE("iron ore", new Texture(Gdx.files.internal("Resource/Iron_ore.png"))),
    GOLD_ORE("gold ore", new Texture(Gdx.files.internal("Resource/Gold_ore.png"))),
    COPPER_BAR("copper bar", new Texture(Gdx.files.internal("Resource/Copper_bar.png"))),
    IRON_BAR("iron bar", new Texture(Gdx.files.internal("Resource/Iron_bar.png"))),
    GOLD_BAR("gold bar", new Texture(Gdx.files.internal("Resource/Gold_bar.png"))),
    IRIDIUM_BAR("iridium bar", new Texture(Gdx.files.internal("Resource/Iridium_bar.png"))),
    WOOD("wood", new Texture(Gdx.files.internal("Resource/Wood.png"))),
    STONE("stone", new Texture(Gdx.files.internal("Resource/Stone.png"))),
    IRIDIUM_ORE("iridium ore", new Texture(Gdx.files.internal("Resource/Iridium_ore.png"))),
    ACORN("acorn", new Texture(Gdx.files.internal("Crafting/Acorn.png"))),
    MAPLE_SEED("maple seed", new Texture(Gdx.files.internal("Trees/Maple_seed.png"))),
    PINE_CONE("pine cone", new Texture(Gdx.files.internal("Trees/Pine_Cone.png"))),
    MAHOGANY_SEED("mahogany seed", new Texture(Gdx.files.internal("Trees/Mahogany_seed.png"))),
    WOOL("Wool", new Texture(Gdx.files.internal("Animals/Wool.png"))),


    CHERRY_BOMB_RECIPE("Cherry Bomb"),
    BOMB_RECIPE("Bomb"),
    MEGA_BOMB_RECIPE("Mega Bomb"),
    SPRINKLER_RECIPE("Sprinkler"),
    QUALITY_SPRINKLER_RECIPE("Quality Sprinkler"),
    IRIDIUM_SPRINKLER_RECIPE("Iridium Sprinkler"),
    CHARCOAL_KILN_RECIPE("Charcoal Kiln"),
    FURNACE_RECIPE("Furnace"),
    SCARECROW_RECIPE("Scarecrow"),
    DELUXE_SCARECROW_RECIPE("Deluxe Scarecrow"),
    BEE_HOUSE_RECIPE("Bee House"),
    CHEESE_PRESS_RECIPE("Cheese Press"),
    KEG_RECIPE("Keg"),
    LOOM_RECIPE("Loom"),
    MAYONNAISE_MACHINE_RECIPE("Mayonnaise Machine"),
    OIL_MAKER_RECIPE("Oil Maker"),
    PRESERVES_JAR_RECIPE("Preserves Jar"),
    DEHYDRATOR_RECIPE("Dehydrator"),
    GRASS_STARTER_RECIPE("Grass Starter"),
    FISH_SMOKER_RECIPE("Fish Smoker"),
    MYSTIC_TREE_SEED_RECIPE("Mystic Tree Seed"),


    FIBER("fiber", new Texture(Gdx.files.internal("Crafting/Fiber.png"))),
    BARN("barn"),
//    BARN("barn", new Texture(Gdx.files.internal("Building/Barn.png"))),  chera eror mide
    BIG_BARN("big barn"),
    DELUXE_BARN("deluxe barn"),
    COOP("coop"),
    BIG_COOP("big coop"),
    DELUXE_COOP("deluxe coop"),
    WELL("well"),
    SHIPPING_BIN("shipping bin"),

    HAY("hay"),
    SHEARS("shears", new Texture(Gdx.files.internal("Tools/Shears/Shears.png"))),
    MILK_PAIR("milk pair"),

    FRIED_EGG("fried egg", new Texture(Gdx.files.internal("Recipe/Fried_EGG.png"))),
    BAKED_FISH("baked fish", new Texture(Gdx.files.internal("Recipe/Baked_fish.png"))),
    SALAD("salad", new Texture(Gdx.files.internal("Recipe/Salad.png"))),
    OMELET("omelet", new Texture(Gdx.files.internal("Recipe/Omelet.png"))),
    PUMPKIN_PIE("pumpkin pie", new Texture(Gdx.files.internal("Recipe/Pumpkin_Pie.png"))),
    SPAGHETTI("spaghetti", new Texture(Gdx.files.internal("Recipe/Spaghetti.png"))),
    PIZZA("pizza", new Texture(Gdx.files.internal("Recipe/Pizza.png"))),
    TORTILLA("tortilla", new Texture(Gdx.files.internal("Recipe/Tortilla.png"))),
    MAKI_ROLL("maki roll", new Texture(Gdx.files.internal("Recipe/Maki_Roll.png"))),
    TRIPLE_SHOT_ESPRESSO("triple shot espresso", new Texture(Gdx.files.internal("Recipe/Triple_Shot_Espresso.png"))),
    COOKIE("cookie", new Texture(Gdx.files.internal("Recipe/Cookie.png"))),
    PANCAKE("pancake"),
    FRUIT_SALAD("fruit salad", new Texture(Gdx.files.internal("Recipe/Fruit_Salad.png"))),
    RED_PLATE("red plate", new Texture(Gdx.files.internal("Recipe/Red_Plate.png"))),
    SALMON_DINNER("salmon dinner", new Texture(Gdx.files.internal("Recipe/Salmon_Dinner.png"))),
    VEGETABLE_MEDLEY("vegetable medley", new Texture(Gdx.files.internal("Recipe/Vegetable_Medley.png"))),
    FARMER_LUNCH("farmer's lunch"),
    SURVIVAL_BURGER("survival burger", new Texture(Gdx.files.internal("Recipe/Survival_Burger.png"))),
    DISH_O_THE_SEA("dish O' the Sea", new Texture(Gdx.files.internal("Recipe/Dish_O%27_The_Sea.png"))),
//    SEAFORM_PUDDING("seaform pudding", new Texture(Gdx.files.internal("Recipe/Seaform_Pudding.png"))),
    MINER_TREAT("miner's treat"),
    PANCAKES("pancakes", new Texture(Gdx.files.internal("Recipe/Pancakes.png"))),
    HASH_BROWNS("hash browns"),
    FARMERS_LUNCH("farmers lunch"),
    SEAFOAM_PUDDING("seafoam pudding", new Texture(Gdx.files.internal("Recipe/Seafoam_Pudding.png"))),
    MINERS_TREAT("miners treat"),

    HARD_WOOD("hard wood"),
    LevelUpFriendship("level up friendship"),
    ANIMAL_BUILDING("animal building"),

    CHICKEN("Chicken"),
    DUCK("Duck" , new Texture(Gdx.files.internal("Animals/Duck.png"))),
    RABBIT("Rabbit", new Texture(Gdx.files.internal("Animals/Rabbit.png"))),
    DINOSAUR("Dinosaur", new Texture(Gdx.files.internal("Animals/Dinosaur.png"))),
    COW("Cow", new Texture(Gdx.files.internal("Animals/Brown_Cow.png"))),
    GOAT("Goat", new Texture(Gdx.files.internal("Animals/Goat.png"))),
    SHEEP("Sheep", new Texture(Gdx.files.internal("Animals/Sheep.png"))),
    PIG("Pig", new Texture(Gdx.files.internal("Animals/Pig.png"))),


    EGG("egg", new Texture(Gdx.files.internal("Foraging/Egg.png"))),
    BIG_EGG("big egg", new Texture(Gdx.files.internal("Animal_Product/Large_Egg.png"))),
    SARDINE("sardine", new Texture(Gdx.files.internal("Fish/Sardine.png"))),
    SALMON("salmon", new Texture(Gdx.files.internal("Fish/Salmon.png"))),
    WHEAT("wheat", new Texture(Gdx.files.internal("Crops/Wheat.png"))),
    LEEK("leek", new Texture(Gdx.files.internal("Crafting/Leek.png"))),
    DANDELION("dandelion", new Texture(Gdx.files.internal("Crafting/Dandelion.png"))),
    MILK("milk", new Texture(Gdx.files.internal("Animal_product/Milk.png"))),
    PUMPKIN("pumpkin", new Texture(Gdx.files.internal("Crops/Pumpkin.png"))),
    //    WHEAT_FLOWER("wheat flower"),
    TOMATO("tomato", new Texture(Gdx.files.internal("Crops/Tomato.png"))),
    CHEESE("cheese", new Texture(Gdx.files.internal("Farming/Cheese.png"))),
    CORN("corn", new Texture(Gdx.files.internal("Farming/Corn.png"))),
    RICE("rice", new Texture(Gdx.files.internal("Crops/Rice.png"))),
    COFFEE("coffee", new Texture(Gdx.files.internal("Artisan_good/Coffee.png"))),
    SUGAR("sugar", new Texture(Gdx.files.internal("Farming/Sugar.png"))),
    POTATO("potato", new Texture(Gdx.files.internal("Farming/Potato.png"))),
    OIL("oil", new Texture(Gdx.files.internal("Crafting/Oil.png"))),
    BLUEBERRY("blueberry", new Texture(Gdx.files.internal("Farming/Blueberry.png"))),
    MELON("melon", new Texture(Gdx.files.internal("Farming/Melon.png"))),
    APRICOT("apricot", new Texture(Gdx.files.internal("Trees/Apricot.png"))),
    GRAPES("grapes"),
    CHERRY("cherry", new Texture(Gdx.files.internal("Trees/Cherry.png"))),
    BANANA("banana", new Texture(Gdx.files.internal("Trees/Banana.png"))),
    MANGO("mango", new Texture(Gdx.files.internal("Trees/Mango.png"))),
    ORANGE("orange", new Texture(Gdx.files.internal("Trees/Orange.png"))),
    PEACH("peach", new Texture(Gdx.files.internal("Trees/Peach.png"))),
    POMEGRANATE("pomegranate", new Texture(Gdx.files.internal("Trees/Pomegranate.png"))),
    APPLE("apple", new Texture(Gdx.files.internal("Trees/Apple.png"))),
    OAK_RESIN("oak resin", new Texture(Gdx.files.internal("Trees/Oak_Resin.png"))),
    MAPLE_SYRUP("maple syrup", new Texture(Gdx.files.internal("Trees/Maple_Syrup.png"))),
    PINE_TAR("pine tar", new Texture(Gdx.files.internal("Trees/Pine_Tar.png"))),
    SAP("sap", new Texture(Gdx.files.internal("Trees/Sap.png"))),
    COMMON_MUSHROOM("common mushroom", new Texture(Gdx.files.internal("Trees/Common_Mushroom.png"))),
    MYSTIC_SYRUP("mystic syrup", new Texture(Gdx.files.internal("Trees/Mystic_Syrup.png"))),
    RED_CABBAGE("red cabbage", new Texture(Gdx.files.internal("Crops/Red_Cabbage.png"))),
    RADISH("radish", new Texture(Gdx.files.internal("Crops/Radish.png"))),
    AMARANTH("amaranth", new Texture(Gdx.files.internal("Crops/Amaranth.png"))),
    KALE("kale", new Texture(Gdx.files.internal("Crops/Kale.png"))),
    BEET("beet", new Texture(Gdx.files.internal("Crops/Beet.png"))),
    PARSNIP("parsnip", new Texture(Gdx.files.internal("Crops/Parsnip.png"))),
    BREAD("bread", new Texture(Gdx.files.internal("Foraging/Bread.png"))),
    CARROT("carrot", new Texture(Gdx.files.internal("Crops/Carrot.png"))),
    EGGPLANT("eggplant", new Texture(Gdx.files.internal("Crops/Eggplant.png"))),
    HASH_BROWN("hash brown"),
    FLOUNDER("flounder", new Texture(Gdx.files.internal("Fish/Flounder.png"))),
    WHEAT_FLOUR("wheat flour", new Texture(Gdx.files.internal("Crops/Wheat_Flour.png"))),
    ANY_FISH("any fish"),
    MIDNIGHT_CARP("midnight carp", new Texture(Gdx.files.internal("Fish/Midnight_Carp.png"))),
    COOPER_TRASHCAN("cooper trashcan"),
    STEEL_TRASHCAN("steel trashcan"),
    GOLD_TRASHCAN("gold trashcan"),
    IRIDIUM_TRASHCAN("iridium trashcan"),
    COPPER_TOOL("copper tool"),
    STEEL_TOOL("steel tool"),
    GOLD_TOOL("gold tool"),
    IRIDIUM_TOOL("iridium tool"),
    PICKLE("pickle"),

    BEER("beer", new Texture(Gdx.files.internal("Artisan_good/Beer.png"))),
    HASH_BROWNS_RECIPE("hash browns recipe"),
    PIZZA_RECIPE("pizza recipe", new Texture(Gdx.files.internal("Recipe/Pizza.png"))),
    OMELET_RECIPE("omelet recipe", new Texture(Gdx.files.internal("Recipe/Omelet.png"))),
    BREAD_RECIPE("bread recipe", new Texture(Gdx.files.internal("Recipe/Bread.png"))),
    PANCAKES_RECIPE("pancakes recipe", new Texture(Gdx.files.internal("Recipe/Pancakes.png"))),
    TORTILLA_RECIPE("tortilla recipe", new Texture(Gdx.files.internal("Recipe/Tortilla.png"))),
    MAKI_ROLL_RECIPE("maki roll recipe", new Texture(Gdx.files.internal("Recipe/Maki_Roll.png"))),
    TRIPLE_SHOT_ESPRESSO_RECIPE("triple shot espresso recipe", new Texture(Gdx.files.internal("Recipe/Triple_Shot_Espresso.png"))),
    COOKIE_RECIPE("cookie recipe", new Texture(Gdx.files.internal("Recipe/Cookie.png"))),

    JOJA_COLA("joja cola"),
    ANCIENT_SEED("ancient seed", new Texture(Gdx.files.internal("Crops/Ancient_Seed.png"))),
    PARSNIP_SEEDS("parsnip seeds", new Texture(Gdx.files.internal("Crops/Parsnip_Seeds.png"))),
    BEAN_STARTER("bean starter", new Texture(Gdx.files.internal("Crops/Bean_Starter.png"))),
    CAULI_FLOWER_SEEDS("cauli flower seeds"),
    POTATO_SEEDS("potato seeds", new Texture(Gdx.files.internal("Crops/Potato_Seeds.png"))),
    STRAWBERRY_SEEDS("strawberry seeds", new Texture(Gdx.files.internal("Crops/Strawberry_Seeds.png"))),
    CALE_SEEDS("cale seeds"),
    CARROT_SEEDS("carrot seeds", new Texture(Gdx.files.internal("Crops/Carrot_Seeds.png"))),
    RHUBARB_SEEDS("rhubarb seeds", new Texture(Gdx.files.internal("Crops/Rhubarb_Seeds.png"))),
    JAZZ_SEEDS("jazz seeds", new Texture(Gdx.files.internal("Crops/Jazz_Seeds.png"))),
    TULIP_BULB("tulip bulb", new Texture(Gdx.files.internal("Crops/Tulip_Bulb.png"))),
    COFFEE_BEANS("coffee beans"),
    TOMATO_SEEDS("tomato seeds", new Texture(Gdx.files.internal("Crops/Tomato_Seeds.png"))),
    PEPPER_SEEDS("pepper seeds", new Texture(Gdx.files.internal("Crops/Pepper_Seeds.png"))),
    WHEAT_SEEDS("wheat seeds", new Texture(Gdx.files.internal("Crops/Wheat_Seeds.png"))),
    SUMMER_SQUASH_SEEDS("summer squash seeds", new Texture(Gdx.files.internal("Crops/Summer_Seeds.png"))),
    RADISH_SEEDS("radish seeds", new Texture(Gdx.files.internal("Crops/Radish_Seeds.png"))),
    MELON_SEEDS("melon seeds", new Texture(Gdx.files.internal("Crops/Melon_Seeds.png"))),
    HOPS_STARTER("hops starter", new Texture(Gdx.files.internal("Crops/Hops_Starter.png"))),
    POPPY_SEEDS("poppy seeds", new Texture(Gdx.files.internal("Crops/Poppy_Seeds.png"))),
    SPANGLE_SEEDS("spangle seeds", new Texture(Gdx.files.internal("Crops/Spangle_Seeds.png"))),
    STARFRUIT_SEEDS("starfruit seeds", new Texture(Gdx.files.internal("Crops/Starfruit_Seeds.png"))),
    SUNFLOWER_SEEDS("sunflower seeds", new Texture(Gdx.files.internal("Crops/Sunflower_Seeds.png"))),
    CORN_SEEDS("corn seeds", new Texture(Gdx.files.internal("Crops/Corn_Seeds.png"))),
    EGGPLANT_SEEDS("eggplant seeds", new Texture(Gdx.files.internal("Crops/Eggplant_Seeds.png"))),
    PUMPKIN_SEEDS("pumpkin seeds", new Texture(Gdx.files.internal("Crops/Pumpkin_Seeds.png"))),
    BROCCOLI_SEEDS("broccoli seeds", new Texture(Gdx.files.internal("Crops/Broccoli_Seeds.png"))),
    AMARANTH_SEEDS("amaranth seeds", new Texture(Gdx.files.internal("Crops/Amaranth_Seeds.png"))),
    GRAPE_STARTER("grape starter", new Texture(Gdx.files.internal("Crops/Grape_Starter.png"))),
    BEET_SEEDS("beet seeds", new Texture(Gdx.files.internal("Crops/Beet_Seeds.png"))),
    YAM_SEEDS("yam seeds", new Texture(Gdx.files.internal("Crops/Yam_Seeds.png"))),
    BOK_CHOY_SEEDS("bok choy seeds", new Texture(Gdx.files.internal("Crops/Bok_Choy_Seeds.png"))),
    CRANBERRY_SEEDS("cranberry seeds"),
    FAIRY_SEEDS("fairy seeds", new Texture(Gdx.files.internal("Crops/Fairy_Seeds.png"))),
    RARE_SEED("rare seed", new Texture(Gdx.files.internal("Crops/Rare_Seed.png"))),
    POWDERMELON_SEEDS("powdermelon seeds", new Texture(Gdx.files.internal("Crops/Powdermelon_Seeds.png"))),
    BOUQUET("bouquet", new Texture(Gdx.files.internal("Special_item/Bouquet.png"))),
    WEDDING_RING("wedding ring", new Texture(Gdx.files.internal("Crafting/Wedding_Ring.png"))),
    VINEGAR("vinegar", new Texture(Gdx.files.internal("Ingredient/Vinegar.png"))),
    DELUXE_RETAINING_SOIL("deluxe retaining soil", new Texture(Gdx.files.internal("Fertilizer/Deluxe_Retaining_Soil.png"))),
    SPEED_GRO("speed-gro"),
    APPLE_SAPLING("apple sapling", new Texture(Gdx.files.internal("Trees/Apple_Sapling.png"))),
    APRICOT_SAPLING("apricot sapling", new Texture(Gdx.files.internal("Trees/Apricot_Sapling.png"))),
    CHERRY_SAPLING("cherry sapling", new Texture(Gdx.files.internal("Trees/Cherry_Sapling.png"))),
    ORANGE_SAPLING("orange sapling", new Texture(Gdx.files.internal("Trees/Orange_Sapling.png"))),
    PEACH_SAPLING("peach sapling", new Texture(Gdx.files.internal("Trees/Peach_Sapling.png"))),
    POMEGRANATE_SAPLING("pomegranate sapling", new Texture(Gdx.files.internal("Trees/Pomegranate_Sapling.png"))),
    BASIC_RETAINING_SOIL("basic retaining soil", new Texture(Gdx.files.internal("Fertilizer/Basic_Retaining_Soil.png"))),
    QUALITY_RETAINING_SOIL("quality retaining soil", new Texture(Gdx.files.internal("Fertilizer/Quality_Retaining_Soil.png"))),
    CAULIFLOWER_SEEDS("cauliflower seeds", new Texture(Gdx.files.internal("Crops/Cauliflower_Seeds.png"))),
    KALE_SEEDS("kale seeds", new Texture(Gdx.files.internal("Crops/Kale_Seeds.png"))),
    GARLIC_SEEDS("garlic seeds", new Texture(Gdx.files.internal("Crops/Garlic_Seeds.png"))),
    RICE_SHOOT("rice shoot", new Texture(Gdx.files.internal("Crops/Rice_Shoot.png"))),
    BLUEBERRY_SEEDS("blueberry seeds", new Texture(Gdx.files.internal("Crops/Blueberry_Seeds.png"))),
    RED_CABBAGE_SEEDS("red cabbage seeds", new Texture(Gdx.files.internal("Crops/Red_Cabbage_Seeds.png"))),
    ARTICHOKE_SEEDS("artichoke seeds", new Texture(Gdx.files.internal("Crops/Artichoke_Seeds.png"))),
    TROUT_SOUP("trout soup", new Texture(Gdx.files.internal("Recipe/Trout_Soup.png"))),
    BAMBOO_POLE("bamboo pole", new Texture(Gdx.files.internal("Tools/Fishing_Pole/Bamboo_Pole.png"))),
    TRAINING_ROD("training rod", new Texture(Gdx.files.internal("Tools/Fishing_Pole/Training_Rod.png"))),
    FIBERGLASS_ROD("fiberglass rod", new Texture(Gdx.files.internal("Tools/Fishing_Pole/Fiberglass_Rod.png"))),
    IRIDIUM_ROD("iridium rod", new Texture(Gdx.files.internal("Tools/Fishing_Pole/Iridium_Rod.png"))),



    DUMMY("dummy"),
    DAFFODIL("daffodil", new Texture(Gdx.files.internal("Crafting/Daffodil.png"))),
    MOREL("morel", new Texture(Gdx.files.internal("Crafting/Morel.png"))),
    SALMON_BERRY("salmon berry", new Texture(Gdx.files.internal("Foraging/Salmonberry.png"))),
    SPRING_ONION("spring onion", new Texture(Gdx.files.internal("Foraging/Spring_Onion.png"))),
    WILD_HORSERADISH("wild horseradish", new Texture(Gdx.files.internal("Foraging/Wild_Horseradish.png"))),
    FIDDLEHEAD_FERN("fiddle head fern", new Texture(Gdx.files.internal("Foraging/Fiddlehead_Fern.png"))),
    RED_MUSHROOM("Red Mushroom", new Texture(Gdx.files.internal("Foraging/Red_Mushroom.png"))),
    SPICE_BERRY("Spice Berry", new Texture(Gdx.files.internal("Foraging/Spice_Berry.png"))),
    SWEET_PEA("Sweet Pea", new Texture(Gdx.files.internal("Foraging/Sweet_Pea.png"))),
    BLACKBERRY("Blackberry", new Texture(Gdx.files.internal("Foraging/Blackberry.png"))),
    CHANTERELLE("Chanterelle", new Texture(Gdx.files.internal("Foraging/Chanterelle.png"))),
    HAZELNUT("Hazelnut", new Texture(Gdx.files.internal("Foraging/Hazelnut.png"))),
    PURPLE_MUSHROOM("Purple Mushroom", new Texture(Gdx.files.internal("Foraging/Purple_Mushroom.png"))),
    WILD_PLUM("Wild Plum", new Texture(Gdx.files.internal("Foraging/Wild_Plum.png"))),
    CROCUS("Crocus", new Texture(Gdx.files.internal("Foraging/Crocus.png"))),
    CRYSTAL_FRUIT("Crystal Fruit"),
    HOLLY("Holly", new Texture(Gdx.files.internal("Foraging/Holly.png"))),
    SNOW_YAM("Snow Yam", new Texture(Gdx.files.internal("Foraging/Snow_Yam.png"))),
    WINTER_ROOT("Winter Root", new Texture(Gdx.files.internal("Foraging/Winter_Root.png"))),
    LARGE_PACK("large backpack"),
    DELUXE_PACK("deluxe backpack"),
    LARGE_MILK("large milk", new Texture(Gdx.files.internal("Animal_product/Milk.png"))),
    LARGE_EGG("large egg", new Texture(Gdx.files.internal("Animal_product/Egg.png"))),
    DUCK_EGG("duck egg", new Texture(Gdx.files.internal("Animal_product/Duck_Egg.png"))),
    DUCK_FEATHER("duck feather", new Texture(Gdx.files.internal("Animal_product/Duck_Feather.png"))),
    RABBITS_FOOT("rabbit foot"),
    DINOSAUR_EGG("dinosaur egg", new Texture(Gdx.files.internal("Animal_product/Dinosaur_Egg.png"))),
    GOAT_MILK("goat milk", new Texture(Gdx.files.internal("Animal_product/Milk.png"))),
    LARGE_GOAT_MILK("large goat milk", new Texture(Gdx.files.internal("Animal_product/Large_Goat_Milk.png"))),
    TRUFFLE("truffle", new Texture(Gdx.files.internal("Animal_product/Truffle.png"))),
    RING("ring", new Texture(Gdx.files.internal("Crafting/Wedding_Ring.png"))),
    DELUXE_RING("deluxe ring"),
    SHAD("shad", new Texture(Gdx.files.internal("Fish/Shad.png"))),
    BLUE_DISCUS("blue discus", new Texture(Gdx.files.internal("Fish/Blue_Discus.png"))),
    SQUID("squid squid", new Texture(Gdx.files.internal("Fish/Squid.png"))),
    TUNA("tuna", new Texture(Gdx.files.internal("Fish/Tuna.png"))),
    PERCH("perch", new Texture(Gdx.files.internal("Fish/Perch.png"))),
    LIONFISH("lionfish", new Texture(Gdx.files.internal("Fish/Lionfish.png"))),
    HERRING("herring", new Texture(Gdx.files.internal("Fish/Herring.png"))),
    GHOSTFISH("ghostfish", new Texture(Gdx.files.internal("Fish/Ghostfish.png"))),
    TILAPIA("tilapia", new Texture(Gdx.files.internal("Fish/Tilapia.png"))),
    DORADO("dorado", new Texture(Gdx.files.internal("Fish/Dorado.png"))),
    LEGEND("legend", new Texture(Gdx.files.internal("Fish/Legend.png"))),
    GLACIER_FISH("glacier fish"),
    ANGLER("angler", new Texture(Gdx.files.internal("Fish/Angler.png"))),
    CRIMSON_FISH("crimson fish"),
    CLOTH("cloth", new Texture(Gdx.files.internal("Crafting/Cloth.png"))),
    HONEY("honey", new Texture(Gdx.files.internal("Artisan_good/Honey.png"))),
    GOAT_CHEESE("goat cheese", new Texture(Gdx.files.internal("Artisan_good/Goat_Cheese.png"))),
    JUICE("juice", new Texture(Gdx.files.internal("Artisan_good/Juice.png"))),
    MEAD("mead", new Texture(Gdx.files.internal("Artisan_good/Mead.png"))),
    PALE_ALE("pale ale", new Texture(Gdx.files.internal("Artisan_good/Pale_Ale.png"))),
    WINE("wine", new Texture(Gdx.files.internal("Artisan_good/Wine.png"))),
    COFFEE_BEAN("coffee bean", new Texture(Gdx.files.internal("Farming/Coffee_Bean.png"))),
    HOPS("hops", new Texture(Gdx.files.internal("Farming/Hops.png"))),
    MAYONNAISE("mayonnaise", new Texture(Gdx.files.internal("Artisan_good/Mayonnaise.png"))),
    DUCK_MAYONNAISE("duck mayonnaise", new Texture(Gdx.files.internal("Artisan_good/Duck_Mayonnaise.png"))),
    DINOSAUR_MAYONNAISE("dinosaur mayonnaise", new Texture(Gdx.files.internal("Artisan_good/Dinosaur_Mayonnaise.png"))),
    TRUFFLE_OIL("truffle oil",new Texture(Gdx.files.internal("Artisan_good/Truffle_Oil.png"))),
    DRIED_MUSHROOM("dried mushroom"),
    DRIED_FRUIT("dried fruit", new Texture(Gdx.files.internal("Artisan_good/Dried_Fruit.png"))),
    RAISIN("raisin"),
    GRAPE("grape", new Texture(Gdx.files.internal("Crops/Grape.png"))),
    SUNFLOWER("sunflower", new Texture(Gdx.files.internal("Crops/Sunflower.png"))),
    JELLY("jelly", new Texture(Gdx.files.internal("Artisan_good/Jelly.png"))),
    SMOKED_FISH("smoothed fish"),
    BLUE_JAZZ("Blue Jazz", new Texture(Gdx.files.internal("Crops/Blue_Jazz.png"))),
    JAZZ("Blue Jazz", new Texture(Gdx.files.internal("Crops/Blue_Jazz.png"))),
    CAULIFLOWER("Cauliflower", new Texture(Gdx.files.internal("Crops/Cauliflower.png"))),
    GARLIC("Garlic", new Texture(Gdx.files.internal("Crops/Garlic.png"))),
    GREEN_BEAN("Green Bean corp", new Texture(Gdx.files.internal("Crops/Green_Bean.png"))),

    RHUBARB("Rhubarb", new Texture(Gdx.files.internal("Crops/Rhubarb.png"))),
    STRAWBERRY("Strawberry", new Texture(Gdx.files.internal("Crops/Strawberry.png"))),
    TULIP("Tulip", new Texture(Gdx.files.internal("Crops/Tulip.png"))),
    UNMILLED_RICE("Unmilled Rice", new Texture(Gdx.files.internal("Crops/Unmilled_Rice.png"))),

    HOT_PEPPER("Hot Pepper", new Texture(Gdx.files.internal("Crops/Hot_pepper.png"))),

    POPPY("Poppy", new Texture(Gdx.files.internal("Crops/Poppy.png"))),

    STARFRUIT("Starfruit", new Texture(Gdx.files.internal("Crops/Starfruit.png"))),
    SUMMER_SPANGLE("Summer Spangle", new Texture(Gdx.files.internal("Crops/Summer_Spangle.png"))),
    SUMMER_SQUASH("Summer Squash", new Texture(Gdx.files.internal("Crops/Summer_Squash.png"))),

    ARTICHOKE("Artichoke", new Texture(Gdx.files.internal("Crops/Artichoke.png"))),

    BOK_CHOY("Bok Choy", new Texture(Gdx.files.internal("Crops/Bok_Choy.png"))),
    BROCCOLI("Broccoli", new Texture(Gdx.files.internal("Crops/Broccoli.png"))),
    CRANBERRIES("Cranberries", new Texture(Gdx.files.internal("Crops/Cranberries.png"))),

    FAIRY_ROSE("Fairy Rose", new Texture(Gdx.files.internal("Crops/Fairy_Rose.png"))),

    YAM("Yam", new Texture(Gdx.files.internal("Crops/Yam.png"))),
    SWEET_GEM_BERRY("Sweet Gem Berry", new Texture(Gdx.files.internal("Crops/Sweet_Gem_Berry.png"))),
    POWDERMELON("Powdermelon", new Texture(Gdx.files.internal("Crops/Powdermelon.png"))),
    ANCIENT_FRUIT("Ancient Fruit corp", new Texture(Gdx.files.internal("Crops/Ancient_Fruit.png"))),




    FERTILIZER("fertilizer", new Texture(Gdx.files.internal("Crafting/Basic_Fertilizer.png"))),
    HOPS_CROP("Hops Crop"),
    FARMING("farming skill icon", new Texture(Gdx.files.internal("Skill/Farming_Skill_Icon.png"))),
    MINING("mining skill icon", new Texture(Gdx.files.internal("Skill/Mining_Skill_Icon.png"))),
    FISHING("fishing skill icon", new Texture(Gdx.files.internal("Skill/Fishing_Skill_Icon.png"))),
    FORAGING("foraging skill icon", new Texture(Gdx.files.internal("Skill/Foraging_Skill_Icon.png"))),

    ;


    private final Texture texture;
    private final String DisplayName;

    ItemType(String DisplayName, Texture texture) {
        this.DisplayName = DisplayName;
        this.texture = texture;
    }
    //todo after completing all of the items texture , remove this
    ItemType(String DisplayName) {
        this.DisplayName = DisplayName;
        texture=null;
    }

    public Texture getTexture() {
        return texture;
    }

    @Override
    public String toString() {
        return name();
    }

    public static ItemType getItemType(String name) {

        for (ItemType itemType : ItemType.values()) {
            if (itemType.getDisplayName().equalsIgnoreCase(name)) {
                return itemType;
            }
        }
        return null;
    }

    public String getDisplayName() {
        return this.DisplayName;
    }
}
